### PR TITLE
feat: [#636] Enable sort by date/popularity/relevance

### LINKED ISSUE #636: Sort by date, pupularity

### PR DESCRIPTION
**Pull request by Michal-Kolomanski**
closes #636

### CODE REVIEW

**Comment by Marcelinna** [comment]
why do we have relevancy for services but for data sources no
image
image

**Comment by Marcelinna** [comment]
is there any difference between most popular and relevance, it returns the same ?

**Comment by Marcelinna** [comment]
Step to reproduce
1. go to https://search-3.docker-fid.grid.cyf-kr.edu.pl/search/all?q=*
2. Go to Publications
3. Set Sort by Relavance
image
4. Go to Data
5. See problem - Publications are displayed
image
6. Go to Services
7. See problem - Publications are displayed
image

**Comment by Marcelinna** [comment]
When I refresh site I often see this 
image

**Comment by Michal-Kolomanski** [comment]
> why do we have relevancy for services but for data sources no? becasue od UA?
> 
> image image

There is no sort by relevance for data sources / bundles / guidelines - the recommender is not handling that. It was also decided to do not to enable this in all catalogs

**Comment by Michal-Kolomanski** [comment]
@agpul @Marcelinna For me, chosen filtering should stay the same as it is set during a collection switching. Currently, when you switch collections, filtering is set on default sorting (which is popularity)

**Comment by Michal-Kolomanski** [comment]
@michal-szostak we are missing here loading logo. Could you describe how its loaded? Any ideas why it is the case?

**Comment by Michal-Kolomanski** [comment]
aai_uid needs to be also added. @tomaszandel consult

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
