### PR TITLE
feat: #791 add source field for publications

### PR DESCRIPTION
**Pull request by Anok666**

### CODE REVIEW

**Review by wujuu — APPROVED** [review]

**Comment by Anok666** [comment]
> I think it shouldn't be visible image

Fix

**Comment by Marcelinna** [comment]
When I select one option source button is changing
image

**Comment by Marcelinna** [comment]
Why I don't see source button for DATA
image

**Comment by Marcelinna** [comment]
@agpul @Michal-Kolomanski 
It is ok that I see one source in OpenAir and two in MP? 
When I click on the Source button I see that the item has DOI, but we don't display it on the resource card, because the DOI field in the data dump is empty?
image

**Comment by wiktorflorian** [comment]
> We show everything we get. From my perspective it is okay. @wiktorflorian could you confirm?

From what I've seen, they do it in OpenAIRE so that if an instance/version of a research product has more than 1 url, they just take 1 from the top. Even if they point to different locations. I can check what the situation is in this exact case though, as if there was a link to the research product somewhere it would go faster for me.

**Pull request closed without merging**
