### PR TITLE
feat: improve suggestions of search bar

### PR DESCRIPTION
**Pull request by biometricsmw**
In this commit, only search suggestions are improved. In separate commit (to separate branch), I will also provide the needful changes in the case of search itself.

### CODE REVIEW

**Comment by eldenkat** [comment]
- [ ] In the results, in addition to the correct ones, items that don't contain the searched phrase at all, are also displayed.

**Comment by biometricsmw** [comment]
One little question, what is the importance of the fields for the search? Because, right now, I changed the implementation of the fuzzy search (only one difference per word is allowed), however, still it shows some strange records. Do we only consider title or other fields (as authors or description) are also considered?

**Comment by biometricsmw** [comment]
@eldenkat could you please take a look at the change? Does it improve the way it the searchbar work?

**Comment by biometricsmw** [comment]
For example I wrote word "perspective" and got the result that (in title) does not contain this phrase - however it is available in the description. Please, take a look at the attached screenshot.
Screenshot 2022-11-21 115545

**Comment by Marcelinna** [comment]
image
word: minh doan does not appear in result prompts

**Comment by eldenkat** [comment]
> @eldenkat could you please take a look at the change? Does it improve the way it the searchbar work?

Yup, ABC and some other phrases are ok. But still smth is wrong, I guess.

**Comment by biometricsmw** [comment]
Thanks @Marcelinna  and @eldenkat for your comments. I assume that the problem lies in the part of the code (qf and numerical values after ^ sign) attached to this comment. However, I need some additional time to check how to fix it (so that it will not destroy the whole search :D ). I will try to experiment with different values for each term (and then we will see whether it is better or not :) ).
Screenshot 2022-11-21 at 16 31 14

**Comment by biometricsmw** [comment]
However, it seems that e.g., abcd-ns was found (for term "resear") because it contains "Research" word in the information :) 
Screenshot 2022-11-21 at 16 36 46

**Comment by biometricsmw** [comment]
@Marcelinna, @michal-szostak  prosiłbym o review

**Comment by biometricsmw** [comment]
This PR will be merged with PR from 272

**Pull request closed without merging**
