### PR TITLE
feat: add AS guide page

### PR DESCRIPTION
**Pull request by maria-j-k**

### CODE REVIEW

**Comment by agpul** [comment]
https://www.figma.com/file/thf78Tiwv9qNGuorwLG1ti/Search?type=design&node-id=980%3A3651&mode=design&t=5TkNPhuXnFe5vcSg-1

**Comment by Marcelinna** [comment]
add dot at the end of sentences

**Comment by Marcelinna** [comment]
@jarekzet please add space
image

**Comment by Marcelinna** [comment]
In Figma I see two buttons Expand all, Hide all, and when the user opens the page see all questions hid. 
image
In PR I don't see buttons, and the first question is open @agpul @aleksandrahojszyk it is ok?
image

**Comment by aleksandrahojszyk** [comment]
Proszę o zmianę nazwy z Advance Search Guide na Advanced Search Guide

**Pull request merged**
