### PR TITLE
feat: Add Sources dropdown

### PR DESCRIPTION
**Pull request by maria-j-k**
closing #791

### CODE REVIEW

**Comment by agpul** [comment]
image
Source should be on the left

**Comment by Marcelinna** [comment]
FIGMA
image

Source not Select Source

**Comment by Marcelinna** [comment]
@agpul @maria-j-k 
It is ok that Openair has another link in the source than Marketplace?
image
image

**Review by tomaszandel — APPROVED** [review]

**Comment by maria-j-k** [comment]
> @agpul @maria-j-k It is ok that Openair has another link in the source than Marketplace? image https://dmtcs.episciences.org/345/pdf http://www.dmtcs.org/dmtcs-ojs/index.php/dmtcs/article/view/66/ https://dmtcs.episciences.org/345 image

I guess this is the scope of Victor's task. 
As for now I was supposed to place the url parameter in sources.
We wanted it to be paired with export / cite functionality

**Review by Marcelinna — APPROVED** [review]

**Comment by wiktorflorian** [comment]
Hey, here's the raw data for "Recognizing Maximal Unfrozen Graphs with respect to Independent Sets is CO-NP-complete" that we obtained from the dump. This instance includes two URLs: `"url":["http://dmtcs.episciences.org/345", "https://doi.org/10.46298/dmtcs.345"]`. I tested both links, and they both direct to the same page.

```python
{
   "author":[
      {
         "fullname":"Abbas, Nesrine",
         "name":"Nesrine",
         "rank":1,
         "surname":"Abbas"
      },
      {
         "fullname":"Culberson, Joseph",
         "name":"Joseph",
         "rank":2,
         "surname":"Culberson"
      },
      {
         "fullname":"Stewart, Lorna",
         "name":"Lorna",
         "rank":3,
         "surname":"Stewart"
      }
   ],
   "bestaccessright":{
      "code":"c_abf2",
      "label":"OPEN",
      "scheme":"http://vocabularies.coar-repositories.org/documentation/access_rights/"
   },
   "collectedfrom":[
      {
         "key":"10|openaire____::6824b298c96ba906a3e6a70593affbf5",
         "value":"Episciences"
      }
   ],
   "contributor":[
      
   ],
   "country":[
      
   ],
   "coverage":[
      
   ],
   "dateofcollection":"2023-08-30T01:57:56+0000",
   "description":[
      "A graph is unfrozen with respect to k independent set if it has an independent set of size k after the addition of any edge. The problem of recognizing such graphs is known to be NP-complete. A graph is maximal if the addition of one edge means it is no longer unfrozen. We designate the problem of recognizing maximal unfrozen graphs as MAX(U(k-SET)) and show that this problem is CO-NP-complete. This partially fills a gap in known complexity cases of maximal NP-complete problems, and raises some interesting open conjectures discussed in the conclusion."
   ],
   "eoscIF":[
      
   ],
   "format":[
      "application/pdf"
   ],
   "id":"50|06cdd3ff4700::00068aa0af6568104c570aa4e82015fd",
   "instance":[
      {
         "accessright":{
            "code":"c_abf2",
            "label":"OPEN",
            "scheme":"http://vocabularies.coar-repositories.org/documentation/access_rights/"
         },
         "alternateIdentifier":[
            {
               "scheme":"doi",
               "value":"10.46298/dmtcs.345"
            }
         ],
         "hostedby":{
            "key":"10|openaire____::6824b298c96ba906a3e6a70593affbf5",
            "value":"Episciences"
         },
         "pid":[
            
         ],
         "publicationdate":"2005-01-01",
         "refereed":"UNKNOWN",
         "type":"Other literature type",
         "url":[
            "http://dmtcs.episciences.org/345",
            "https://doi.org/10.46298/dmtcs.345"
         ]
      }
   ],
   "keywords":[
      "independent set",
      "[INFO.INFO-DM] Computer Science [cs]/Discrete Mathematics [cs.DM]",
      "unfrozen",
      "co-NP-complete",
      "extremal",
      "graph"
   ],
   "language":{
      "code":"eng",
      "label":"English"
   },
   "lastupdatetimestamp":1694244770731,
   "maintitle":"Recognizing Maximal Unfrozen Graphs with respect to Independent Sets is CO-NP-complete",
   "originalId":[
      "oai:episciences.org:dmtcs:345"
   ],
   "pid":[
      
   ],
   "publicationdate":"2005-01-01",
   "publisher":"episciences.org",
   "source":[
      
   ],
   "subject":{
      
   },
   "type":"publication"
}
```

**Comment by jarekzet** [comment]
added styling:

image

**Pull request merged**
