### PR TITLE
search results box css mods

### PR DESCRIPTION
**Pull request by jarekzet**
mods of CSS for search reslut list

### CODE REVIEW

**Comment by Marcelinna** [comment]
1. The text should be in bold and capital letters
image

**Comment by Marcelinna** [comment]
2. Delete yellow hover from "show more" button

**Comment by Marcelinna** [comment]
3. Reme the comma
image

**Comment by Marcelinna** [comment]
4. Move the elements apart
image

**Comment by jarekzet** [comment]
all mods are done. Sometimes commas are added in author names - it ins not connected with template:

image

**Review by Marcelinna — CHANGES_REQUESTED** [review]
please see above

Update: the problem is not related to pr

**Review by Marcelinna — APPROVED** [review]

**Review by danielkryska — APPROVED** [review]

**Pull request merged**
