### PR TITLE
fix: [#656] sort by relevance

### LINKED ISSUE #656: Fix the shortcomings in sorting
FIx: 
- aai_uid in sort by relevance @tomaszandel @Michal-Kolomanski 
- handle empty resources list after sorting by relevance @Michal-Kolomanski

### PR DESCRIPTION
**Pull request by Michal-Kolomanski**
closes #656

### CODE REVIEW

**Comment by Marcelinna** [comment]
Why for training I have one result? when I select sort by relevancy
image

image

**Comment by Marcelinna** [comment]
1. Go to the Services collection
2. Select Discover Research Output
3. Type data to the search bar
image
4. Click keywords "data archive"
5. See problem - no data
image

**Comment by Michal-Kolomanski** [comment]
> Why for training I have one result? when I select sort by relevancy image
> 
> image

Now there are 4 trainings. I expected it to be empty because we have catalog ID in the training IDs themselves, and Poznan does not have that.  @wziajka did you change something in the RS from Poznan? E.g. data?

**Comment by Michal-Kolomanski** [comment]
> 1. Go to the Services collection
> 2. Select Discover Research Output
> 3. Type data to the search bar
>    image
> 4. Click keywords "data archive" from the first service result on the list
> 5. See problem - no data
>    image

the same case as batteries and open access. Not the scope of this ticket

**Comment by agpul** [comment]
> > 1. Go to the Services collection
> > 2. Select Discover Research Output
> > 3. Type data to the search bar
> >    image
> > 4. Click keywords "data archive" from the first service result on the list
> > 5. See problem - no data
> >    image
> 
> the same case as batteries and open access. Not the scope of this ticket

It works on PR: #670

**Review by Anok666 — APPROVED** [review]

**Pull request merged**
