### PR TITLE
feat: #718 single api endpoint for filters

### PR DESCRIPTION
**Pull request by Barmin93**
Files related to external API requests (including SOLR has been changed). Please check for potential regressions.

### CODE REVIEW

**Review by tomaszandel — APPROVED** [review]
looks ok

**Comment by agpul** [comment]
image
no filter visible!

**Comment by Marcelinna** [comment]
Please check this
1. I am on guidelines collection
image
2. Change collection to bundle - I see request to /api/web/search-result and one/api/web/search-filters
image
3. Select on of the filetrs - I see only request to /api/web/search-result - @michal-szostak @Barmin93 it is ok?
image
4. Turn of seletced filter - I see two request 
image
5. Select agian filter from step 3 - I see two request 
image

**Comment by Marcelinna** [comment]
the same situation as above
1. Go to Data collection
2. Click on the tag - I see one request 
image
3. Click another tag, I see two request

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
image

**Comment by Marcelinna** [comment]
@michal-szostak When I click on filter for training I see 4 request, I should see 2 ?
image

**Comment by michal-szostak** [comment]
@Marcelinna - in trainings those additional requests come from "Durantion" and "datetime" filters (there are both there). So this is in line with what is to be expected.

**Comment by Marcelinna** [comment]
@michal-szostak we have other behaviour than on production
image
image

**Comment by Marcelinna** [comment]
When I type something in a basic search I see that filters have a different order than in production enviroment


image

**Comment by Marcelinna** [comment]
@michal-szostak 
image

**Comment by Marcelinna** [comment]
@agpul @aleksandrahojszyk @Karolina9824 
when filters do not have any value to select when narrowing down values, the filter header disappears

image

**Comment by agpul** [comment]
> @agpul @aleksandrahojszyk @Karolina9824 when filters do not have any value to select when narrowing down values, the filter header disappears
> 
> image

Yes, this is good behavior. We wanted to do this in the other issue.

**Comment by michal-szostak** [comment]
> When I type something in a basic search I see that filters have a different order than in production environment
> 
> image

This is not changed, but I believe this behaviour is correct - the sorting is done first by `count` (number of documents) and second alphabetically.

The original behavior was a little bit undetermined.

@agpul - I can hack away to make it work the same, but I think that this is clearer...

**Comment by agpul** [comment]
> > When I type something in a basic search I see that filters have a different order than in production environment
> > image
> 
> This is not changed, but I believe this behaviour is correct - the sorting is done first by `count` (number of documents) and second alphabetically.
> 
> The original behavior was a little bit undetermined.
> 
> @agpul - I can hack away to make it work the same, but I think that this is clearer...

We agreed during the daily with Roksana, that this behaviour is OK and can stay.

**Comment by Marcelinna** [comment]
beta 
image
pr
image

We had PR that we wanted language sortable alphabetically
https://github.com/cyfronet-fid/eosc-search-service/issues/603

**Comment by Marcelinna** [comment]
beta - clear button is visible 
image
pr 
image

**Comment by Marcelinna** [comment]
1. Go to Training and check open access filter 
image
2. Change to Services - not all filters are visible
image

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
