### PR TITLE
feature: [#153] improve pagination

### PR DESCRIPTION
**Pull request by michal-szostak**

### CODE REVIEW

**Comment by Marcelinna** [comment]
@agpul 

image
Do we want to add a button to redirect to the last page with results?

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

Problem with automatic scroll to the top of the page

Steps to reproduce
1. Go to /search/publications?q=*
2. Scroll page to bottom navigation
3. Click on page "2" - take a look at how the user is moved to the top of the page
4. Click on the page "3" - take a look at how the user is moved to the top of the page
5. Click on the page "4" - the way to move to the top of the page is different (you can see scrolling up)

**Comment by Marcelinna** [comment]
whether the page number in the url should not be equal to the pagination page number?

image

**Comment by agpul** [comment]
> @agpul
> 
> image Do we want to add a button to redirect to the last page with results?

Yes, it should be added.

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

After turning on the filter, the page on pagination does not change to the first

Steps to reproduce
1. Go to /search/trainings?q=*
3. Click on pagination page "3"
4. Turn on filter (e.g Content Type - HTML)
5. See problem - user is still on page "3" 
image

Expected behaviour - when filter is turn on, page should be "1"

**Comment by Marcelinna** [comment]
- [ ]  QA
- [ ] DEV

Problem with the number of displayed pages

Steps to reproduce
1. Go to /search/trainings?q=* 
image
2. Go to the last page on pagination 
image
3. Go to the first page on pagination 
 image
5. Go to the last page on pagination 
image

In step two the last page is "4", in step five the last page is "6"

**Comment by danielkryska** [comment]
old issue

**Pull request closed without merging**
