### PR TITLE
feat: move providers to top menu

### PR DESCRIPTION
**Pull request by maria-j-k**
closing #900

### CODE REVIEW

**Review by tomaszandel — APPROVED** [review]

**Comment by Marcelinna** [comment]
step to reproduce
1. Go to SS
2. Click on the Provider tab
3. Click on the All Catalog tab 
4. See problem - Provider tab is higlighted

image

**Comment by Marcelinna** [comment]
When I click on EOSC Marketplace Resources when I am on Provider tab I don't go to the All Catalog tab
image

**Comment by jarekzet** [comment]
added search box styling:

image

**Review by Marcelinna — APPROVED** [review]

**Comment by agpul** [comment]
@aleksandrahojszyk 
image
when I am on the providers tab, the main menu with all catalogs, etc. should be visible or not?

**Comment by aleksandrahojszyk** [comment]
https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/EOSC-Design?type=design&node-id=5255%3A6955&mode=design&t=iGgxaWxTawMKkjX0-1 

changes: 
1 no dropdown view on the search bar 
2 no categories (all catalogs, publication etc) visible on the provider search view

**Comment by Marcelinna** [comment]
1. Go to Providers
2. Show Advance serach
3. Go to EOSC Marketplace Resources
4. See problem
image

**Comment by Marcelinna** [comment]
When I expand the advanced search I see an empty value.
image
beta
image

**Pull request merged**
