### PR TITLE
feat: #693 html structure changed

### PR DESCRIPTION
**Pull request by Anok666**
https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/Marketplace-EOSC?type=design&node-id=60-2227&mode=design&t=V43vZlbG9qAFpD1v-0

### CODE REVIEW

**Comment by Marcelinna** [comment]
some problem with IG
  
image

**Comment by Marcelinna** [comment]
Section right should be changed similar to section Creator 
image
FIGMA
image

**Comment by Marcelinna** [comment]
should be equla 
image

**Comment by Marcelinna** [comment]
Add underline
image

**Comment by Marcelinna** [comment]
- [ ] QA
Add section Resource Details
image

**Review by Michal-Kolomanski — APPROVED** [review]

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
