### PR TITLE
feat: [#754] Remove bundles from top of search

### LINKED ISSUE #754: Hide bundles from the top of search
Currently, bundles are at the top of search results
image

The scope of the ticket is to: 
- when search phrase and filters are not used - hide bundles from search results.

When bundles will have a dedicated page, they would not be hidden anymore.

### PR DESCRIPTION
**Pull request by wujuu**
Closes #754.

This is a workaround. Fix once bundles are presentable again.

How to test:
1. Go to /search/all
2. Bundles should be at the very bottom of the list (this will be impossible to check manually, unless you go through X amount of pages)
3. Bundles should still be present when you search for them.

### CODE REVIEW

**Comment by Marcelinna** [comment]
bundle still high on the list
image

**Review by tomaszandel — CHANGES_REQUESTED** [review]
this sort will not fix it, if we want to be sure, i would recommend based on extend_results_with_bundles , get al bundles from search results and append them to the end when creating putput in create_output function out['results'] take all except bundles and + `    bundle_results = list(
        fillter(lambda doc: doc["type"] == "bundle", res_json["response"]["docs"])
    )`

**Comment by wujuu** [comment]
@tomaszandel I will try your approach but it works with all other datatypes (tested locally) - why would it not work on bundles?

Granted I don't have any bundles in my local dataset so there might be something different about them

**Comment by wujuu** [comment]
@tomaszandel my solution should work now. The problem was not in the sort query but in the `if collection == "all_collection"` condition. We have different prefixes for beta collections so it was not working on PR but was working for me locally.

**Review by Marcelinna — APPROVED** [review]

**Review by tomaszandel — APPROVED** [review]

**Pull request merged**
