### PR TITLE
Search results improvements

### PR DESCRIPTION
**Pull request by jarekzet**
Added mods on the search results list:

image
https://www.figma.com/file/pTiscgrb4ie8R57vJmEhyL/Boxy-Redesign?type=design&node-id=7-2879&mode=design&t=3kJavuus7ieNTgsJ-4

### CODE REVIEW

**Comment by agpul** [comment]
> Problem with icons image

I think that there is a problem with the type because as you can see the color is grey on this box ... (Publications are yellow)

**Comment by Marcelinna** [comment]
why don't all boxes have a yellow edge for publications? 
image

**Comment by Marcelinna** [comment]
According to the FIGMA, word "DOI" should be in blue box 
image

**Comment by Marcelinna** [comment]
Why I see different icon for data collection ?
image

**Comment by Marcelinna** [comment]
icon for providers 
image

**Comment by Marcelinna** [comment]
box color and icon for bundles
image

**Comment by Michal-Kolomanski** [comment]
@jarekzet please fix the commit messages according to [conventional commits guideline](https://www.conventionalcommits.org/en/v1.0.0-beta.2/#:~:text=Commits%20MUST%20be%20prefixed%20with,bug%20fix%20for%20your%20application.).
And also please fix UI styles

**Review by michal-szostak — APPROVED** [review]

**Pull request merged**
