### PR TITLE
feat: #535 include bundles in the search service front

### PR DESCRIPTION
**Pull request by Anok666**
in progress
https://github.com/cyfronet-fid/eosc-search-service/issues/535

### CODE REVIEW

**Comment by Marcelinna** [comment]
Is it possible to scroll to bundle? when I click on it in SS

**Comment by Marcelinna** [comment]
image

**Comment by Marcelinna** [comment]
image
image
You don't have data to display second offer?

**Comment by Marcelinna** [comment]
In Figma, I see a filter for Access right and Language, but I don't see a filter Dedicated for.
You don't have data?
@agpul we should keep filter Dedicated for ?
image

**Comment by Marcelinna** [comment]
image

**Comment by Marcelinna** [comment]
View of bundle in All catalogs
image

**Comment by agpul** [comment]
> In Figma, I see a filter for Access right and Language, but I don't see a filter Dedicated for. You don't have data? @agpul we should keep filter Dedicated for ? **FIGMA** image **PR** image

If we have this field in the data, we can leave it.

**Comment by Marcelinna** [comment]
image
Please change position "show more" button, do the same as for other resources.

**Comment by Marcelinna** [comment]
beta
image
pr - additional underline
image

**Comment by Marcelinna** [comment]
image

**Review by michal-szostak — APPROVED** [review]

**Review by agpul — APPROVED** [review]

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
