### PR TITLE
New eosc pl styling

### PR DESCRIPTION
**Pull request by jarekzet**
Added new styling due to #1392

image

### CODE REVIEW

**Review by Michal-Kolomanski — APPROVED** [review]
👏 👏 👏

**Comment by Michal-Kolomanski** [comment]
This styling should be applied also to recommendations at the bottom (EU scope)
image

**Comment by Michal-Kolomanski** [comment]
As @AlicjaSwierad pointed out there is a color mismatch
image

**Comment by AlicjaSwierad** [comment]
> As @AlicjaSwierad pointed out there is a color mismatch image

Icone ⤵️
download

**Comment by AlicjaSwierad** [comment]
> URL


Pink: FEF2F4
image

green: E4F9FA
image

**Comment by AlicjaSwierad** [comment]
Change:

- [ ] logo 
image

- [ ] move to the left side 
image
as in figma:
image

- [ ] add button (providers, projects, organisations itp)
image

- [ ] add button style
border-radius: 1.5rem;

opacity: 0.9;
background: var(--Background-Green-Accessable, #24727B);
backdrop-filter: blur(300px);
image


- [ ] remove baner from search 
image

**Pull request merged**
