### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by danielkryska**
- [x] remove `Research steps` filter from `All catalogs`
- [x] fix: restore tree caret in multi-select 
image

- [x] chore: use platforms instead of related_platforms field in `service` and `data source` #238 
image
image

- [x] feat: remove the `Direct download` button from the training detail page
image

- [x] fix: multi-select lazy loading
image

- [x] feat: use a green padlock on the open access label and an orange one for all other access types #375 
image
image

### CODE REVIEW

**Comment by danielkryska** [comment]
image

**Comment by Marcelinna** [comment]
tree is not visible 
image

**Comment by Marcelinna** [comment]
Platforms not similar to MP
image
image

**Comment by Marcelinna** [comment]
Direct download in training is visible
image

**Comment by Michal-Kolomanski** [comment]
> tree is not visible image

Weird I have a proper tree visualization 
image

**Review by Marcelinna — APPROVED** [review]

**Review by Michal-Kolomanski — APPROVED** [review]
The code looks good. Many issues were fixed here. :clap: 
@Marcelinna please also test those

**Pull request merged**
