### PR TITLE
957 main menu redesign

### LINKED ISSUE #957: Redesign of the main menu in the SS
Acceptance criteria:
- [ ] As a User I would like to see the main menu according to the Figma: https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/EOSC-Design?type=design&node-id=5358%3A13775&mode=design&t=55P5ojq3wQHwqhVK-1

### PR DESCRIPTION
**Pull request by jarekzet**
closes #957 

image

### CODE REVIEW

**Comment by aleksandrahojszyk** [comment]
Screenshot 2023-11-03 at 09 45 22
1. Icon for All catalogs is broken -> I will share it in the next comment
2. 040F81 color of the selected category
3. Selected font weight change from 700-> 600  
5. Mobile view should not be separated between rows and each of the component should be not a rectangle but a square
Screenshot 2023-11-03 at 09 47 42

**Comment by Karolina9824** [comment]
1. Icon for Other is broken -> trimmed
2.Icons-> Trainings, bundles,ig and other -> The icon are too low compared to the rest, it should be centered
3.Text--> Trainings, bundles,ig and other -> The text are too high compared to the rest (+/- 1,2px), it should be centered

**Comment by Marcelinna** [comment]
@agpul @aleksandrahojszyk 
the order should be as in FIGMA?
Bundle and Guidelines should have beta label?
@jarekzet Please change Others to Others Products

image

**Comment by agpul** [comment]
> @agpul @aleksandrahojszyk the order should be as in FIGMA? Bundle and Guidelines should have beta label? @jarekzet Please change Others to Others Products
> 
> image

1. Other should look like in FIGMA
2. Beta - if it is possible to add we can add, but we decided that if it is not possible or will look bad we should remove it

**Comment by jarekzet** [comment]
Added mods according to comments:

image

**Comment by jarekzet** [comment]
Added tabs new order

**Review by tomaszandel — APPROVED** [review]

**Pull request merged**
