### PR TITLE
fix: hide show more btn on short txt

### LINKED ISSUE #231: Show more button - redundant
sometimes the button show more doesn't show anything

image
image

### PR DESCRIPTION
**Pull request by danielkryska**
closes #231

### CODE REVIEW

**Comment by danielkryska** [comment]
image

**Comment by danielkryska** [comment]
image

**Review by agpul — CHANGES_REQUESTED** [review]
1.  Before clinking on "show more"
image
2. After clicking on show more:
image


From my point of view it doesn't work

**Comment by danielkryska** [comment]
Yes, my bad. Sorry.
image

**Review by agpul — APPROVED** [review]

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
