### PR TITLE
feat: [#859, #862] Global filters

### PR DESCRIPTION
**Pull request by wujuu**
Added global filters as specifed in #859 and #862. 

NOTE: Mappings of ids into friendly names are hardcoded right now. We should create a separate issue for fetching them dynamically, once we have everything in place in SOLR. (Catalogues, for example, do not have their own collection to refer for friendly names to)

https://search-pr-1005.docker-fid.grid.cyf-kr.edu.pl

### CODE REVIEW

**Comment by Michal-Kolomanski** [comment]
@wziajka I dont see any comment with an URL SS instance of this PR. Is frontend successfully built?

**Review by tomaszandel — APPROVED** [review]

**Comment by Marcelinna** [comment]
I don't see Catalog filter for Publications, Data, Software and Others 
it is intentional?
"As a user I would like to use a catalog filter for all Research Products (manually set: "EOSC")"

**Comment by Marcelinna** [comment]
'Show all" in filters will be added in other pr?

**Comment by wujuu** [comment]
> I don't see Catalog filter for Publications, Data, Software and Others it is intentional? "As a user I would like to use a catalog filter for all Research Products (manually set: "EOSC")"

okay I thought we were talking about "all collection". I will fix that

**Comment by wujuu** [comment]
@tomaszandel @Marcelinna let's not merge this yet, because we've noticed optimizaiton issues and also some bugs that need solving

**Comment by Marcelinna** [comment]
When I click "Clear all filters", I don't see changes
image

**Comment by wujuu** [comment]
@jarekzet please try to adjust the styling to the preview - I've done what I could but there are certain things that I haven't found how to manipulate, becase the component used is from the library - not fully custom. 

Let me know what can be done so we can discuss further steps

**Comment by eldenkat** [comment]
To do:

- [ ] Change the name Catalog  → Community Catalog 
- [ ] Change the name All Catalogs  → All Resources
- [ ] Community Catalog filter displayed only in - all resources/services/data sources/IG/training/bundle
- [ ] Delete EOSC Catalog
- [ ] Add tooltip to datasource filter (TBD) 
- [ ] Data source filter - displayed only in publications/data/software/other
- [ ] Delete [zero] items from the dropdown list in both filters
- [ ] Change the text "show all" TBD

**Comment by jarekzet** [comment]
added styling for dropdown filter 
image

**Comment by Marcelinna** [comment]
I dont see result record
image

**Comment by Marcelinna** [comment]
Please rebase this pr do develop

**Comment by eldenkat** [comment]
Need to remove EOSC catalog:
Screenshot 2023-11-21 at 08 09 05

**Comment by Marcelinna** [comment]
problem with navigation
image

**Comment by Marcelinna** [comment]
We dont have a catalog for bundle?
image

**Comment by Marcelinna** [comment]
@wujuu I don't see changes  --> Change the text "show all" to "All selection"

**Comment by eldenkat** [comment]
Empty catalog should be hidden:
Screenshot 2023-11-21 at 08 14 59

**Comment by Marcelinna** [comment]
Can you add better name for filter ?
image

**Comment by Marcelinna** [comment]
improve the appearance of the box
image

**Comment by Marcelinna** [comment]
Please Add catalog filter for Providers

**Comment by wujuu** [comment]
> improve the appearance of the box
> image

in what way? Can you be more specific?

**Comment by wujuu** [comment]
> Can you add a better name for the selected filter ?
> image

you mean for the active filter selection?

**Comment by wujuu** [comment]
> problem with navigation
> image

I don't see this issue on my screen (when maximised), only when I shrink the viewport size. I don't think this has anything to do with changes in this PR

**Comment by wujuu** [comment]
> We dont have a catalog for bundle?
> image

I think we don't - let's ask @Michal-Kolomanski or @wiktorflorian

**Comment by eldenkat** [comment]
Change Show All to All Selection:

Screenshot 2023-11-21 at 08 48 14

**Comment by wiktorflorian** [comment]
> > We dont have a catalog for bundle?
> > image
> 
> I think we don't - let's ask @Michal-Kolomanski or @wiktorflorian

To be fair, I never worked with bundles, @Michal-Kolomanski  should be the one to ask.

**Comment by eldenkat** [comment]
Need to align filter names. The active filter should display full catalog name:

Screenshot 2023-11-21 at 09 01 00

**Comment by Marcelinna** [comment]
tooltip dla data sources
The list provided in this filter does not include of all the data sources published in EOSC, only those harvested in OpenAIRE Research Graph. Such data sources make their research products discoverable and available in EOSC.

**Comment by Marcelinna** [comment]
Data Source: eosc.lindatclariah-cz.6dc98fcb5294282acf3d92f3a.
image

**Comment by Karolina9824** [comment]
figma: https://www.figma.com/file/wFzD4qH6SwpfCybte3pLlb/EOSC-DRAFTS?type=design&node-id=2636%3A24877&mode=design&t=oT9mWax1ieU8lIV1-1

**Comment by Karolina9824** [comment]
Jarek, please change color for hover from #5EA7F8 to #3D4DB6

**Comment by jarekzet** [comment]
Added mods for dropdown (right padding, arrow position, and hover color)

image

**Comment by Marcelinna** [comment]
1. Go to Data and select all Data source
image
2. I go to Software
image

@wujuu @agpul In chips I see more than filters, it is ok ? for this filter too ?

**Review by Anok666 — APPROVED** [review]

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
