### PR TITLE
feat: [#785] Expand results metadata

### LINKED ISSUE #785: Add additional fields to each type of product
Acceptance criteria:
- As a User, I would like to see fields as a filter for other:
- [x] Author
- [ ] Publisher
- [ ] Scientific Domain
- [x] Identifier 
- As a User, I would like to see fields as a filter for publications:
- [x] Author
- [ ] Journal
- [x] Publisher
- [ ] Scientific Domain
- [x] Identifier
- As a User, I would like to see fields as a filter for Data:
- [x] Author
- [x] Publisher
-  [ ] Scientific Domain
- [x] Identifier
- As a User, I would like to see fields as a filter for Software:
- [x]  Author
- [x] Publisher
- [ ] Scientific Domain
- As a User, I would like to see fields as filters for Training:
- [x] Author
- [x] Content Type
- As a User, I would like to see fields as filters for Services:
- [x] Organisation
- [x] Scientific Domain
- As a user, I would like to see fields as filters for Data sources:
- [x] Organisation
- [x] Scientific Domain
- As a user, I would like to see fields as filters for IG:
- [x] Provider

!!!IMPORTANT
Make sure that all fields are added to the proper positions according to Figma design:
https://www.figma.com/file/pTiscgrb4ie8R57vJmEhyL/Boxy-Redesign?type=design&node-id=7-2879&mode=design&t=3kJavuus7ieNTgsJ-4

### PR DESCRIPTION
**Pull request by wujuu**
Closes #785

### CODE REVIEW

**Comment by jarekzet** [comment]
Added CSS mods to metadata list

image

**Review by tomaszandel — APPROVED** [review]

**Comment by wujuu** [comment]
@agpul Journal is not present in the prod data. Scienfitifc domains are handled by @Michal-Kolomanski in https://github.com/cyfronet-fid/eosc-search-service/pull/829

**Comment by Marcelinna** [comment]
@jarekzet 
problem with css
image

**Comment by Marcelinna** [comment]
document type not occurred for publications in AC
image

**Comment by agpul** [comment]
@jarekzet please remove commas for scientific domains and authors: 
image

**Comment by wujuu** [comment]
@Marcelinna please review - new stylings are applied by @jarekzet

**Comment by wujuu** [comment]
> Resource type not occurred for training in AC image

See above comment

**Comment by Marcelinna** [comment]
@jarekzet shouldn't it start in the same place?
image

**Comment by Marcelinna** [comment]
after merge this https://github.com/cyfronet-fid/eosc-search-service/pull/830 check if view is according with FIGMA
image

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
