### PR TITLE
fix: [#524] User is redirected to the top of the page after pagination

### LINKED ISSUE #524: When changing a page on pagination, the user stays at the bottom of the page
1. Go to https://search.marketplace.eosc-portal.eu/search/all?q=*
2. Change page from 1 to 2 
3. See problem - the user stays at the bottom of the page. The user should be redirected to the top of the page

### PR DESCRIPTION
**Pull request by wujuu**
User is now redirected to the top after chaging the page.

Closes #524

### CODE REVIEW

**Review by tomaszandel — APPROVED** [review]

**Comment by Michal-Kolomanski** [comment]
> Step to reproduce FIREFOX (on CHROME is ok)
> 
> 1. Change on pagination page from 1 to 2 - the user is on top of the page
> 2. Change on pagination page from 2 to 3 - the user is on top of the page
> 3. Change on pagination page from 3 to 4 - the user is at bottom of the page

I have the same issue on Firefox :/ 
Furthermore, going to 5/10/15/... stays also at the bottom

**Review by Michal-Kolomanski — CHANGES_REQUESTED** [review]
Firefox issues :/

**Comment by wujuu** [comment]
I've added a small delay to the scroll to make sure the page is rendered correctly before scrolling - that might've been the issue in Firefox

**Review by Michal-Kolomanski — APPROVED** [review]
LGTM now :D 
@Marcelinna, please do your review once more.

**Pull request merged**
