### PR TITLE
feat: add data sources

### LINKED ISSUE #290: Add Data sources to the Serach Service
As a scope of this issue, the Data Sources should be reachable from the SS level. In the first iteration create schema and solr configuration using dump provided by @wziajka (taken from PC API) - 27 records.

**Acceptance criteria:**
- [ ] As a User I can see the "Data sources" tab in the Search Service
- [ ] As a User I can find the data sources using the Search Bar in the Search Service 
- [ ] As a User I can find the Data sources in "All catalogs" tab
- [ ] As a User I can find the Data sources in "Data sources" tab
- [ ] As a User I can see: 
image

- [ ] As a User I can have the same filter for Data Sources as I have for Services
- [ ] As a User I can click on the Data Source title and I will be redirected to the Data Source page in MP

### PR DESCRIPTION
**Pull request by danielkryska**
closes #290

image

### CODE REVIEW

**Comment by Marcelinna** [comment]
@agpul Whether scientific domain should be separated with commas, sometimes a comma is present ?
image

**Comment by agpul** [comment]
> @agpul Whether scientific domain should be separated with commas, sometimes a comma is present ? image

We leave it as it is now.

**Review by Michal-Kolomanski — APPROVED** [review]
LGTM

**Review by michal-szostak — APPROVED** [review]

**Review by Michal-Kolomanski — CHANGES_REQUESTED** [review]
Please handle `data source` type.

When you click on a data source:
```
{"detail":[{"loc":["query","resource_type"],"msg":"unexpected value; permitted: 'service', 'publication', 'dataset', 'training', 'software'","type":"value_error.const","ctx":{"given":"data source","permitted":["service","publication","dataset","training","software"]}}]}
```

**Comment by Marcelinna** [comment]
image

**Review by Michal-Kolomanski — APPROVED** [review]

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
