### PR TITLE
feat: [#599] Change the date range filter to use year only

### LINKED ISSUE #599: Change to way of displaying the Year range filters in data, OTHER and publications tab
Acceptance criteria:
- [ ] As a user I want to select the year range based on the year not the full date as it is now (APPLICABLE ONLY FOR DATA, PUBLICATION and Other TYPE)

Here now I can select the full date, I should be able to choose only year
image

### PR DESCRIPTION
**Pull request by wujuu**
Closes #599.

### CODE REVIEW

**Comment by Marcelinna** [comment]
It is possible to delete T00:00:00Z  from label?
image

**Comment by michal-szostak** [comment]
@wujuu - I've changed owner of this issue to @Barmin93 . The issue is that the year range should be applicable only to specific collections (Publications, Other, Data) not all of them.

**Comment by wujuu** [comment]
@michal-szostak  Well it's the only ones that do have the date range filter (besides trainings, my bad) so I just assumed we want that for every filter.

@Barmin93 can you use my implementation and tweak it so it's only applicable to these filters?

**Comment by Barmin93** [comment]
@wujuu Sure. Will be tweaked according to specification.

**Comment by Barmin93** [comment]
@michal-szostak Added separation for filters.  As for changing the display for dates - I think it would be better to do this in a separate ticket and PR, as it's a little bit more complicated than I initially thought.  Would need some time to figure out how to do this properly.

**Comment by wujuu** [comment]
Can you squash and rebase your commits? IMO rebase is much cleaner than messy merge commits

**Comment by Barmin93** [comment]
@wujuu Done. I thought in github it's similar to DevOps/GitLab, where you can specify merging strategy, when you're clicking "Merge pull request".  Didn't know it must be done "by hand".

**Review by tomaszandel — APPROVED** [review]

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
