### PR TITLE
feat: add no-data and no-results views

### PR DESCRIPTION
**Pull request by maria-j-k**

### CODE REVIEW

**Review by tomaszandel — APPROVED** [review]

**Comment by jarekzet** [comment]
added styling

image

**Comment by agpul** [comment]
> added styling
> 
> image

@maria-j-k Can you change from the" Clear all filters" to "Clear all" and add the possibility to clear filters and/or search phrases in the main search? this view is valid for this two cases

**Comment by agpul** [comment]
image
Please remove.

**Comment by Marcelinna** [comment]
Can you add space?
image

**Comment by Marcelinna** [comment]
1. Go to SS
2. See no data
3. Change All catalogs, to Publication, Publication to Services, Services to Datasources
4. I noticed That I have No data, but I see filters for datasources
image

**Comment by Marcelinna** [comment]
I don't see filters for providers, it is a problem this pr?
image

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
