### PR TITLE
1249 new search bar

### PR DESCRIPTION
**Pull request by jarekzet**
closes: #1249 

image

image

### CODE REVIEW

**Comment by Marcelinna** [comment]
For collection where we don't have advance search I still see Advance search guide
image

**Comment by aleksandrahojszyk** [comment]
Screenshot 2024-03-08 at 09 03 50
when on hover, button should not get semi-transparent @AlicjaSwierad please prepare how it should behave

**Comment by Marcelinna** [comment]
please make bigger box where Keywords word exist
image

**Comment by Marcelinna** [comment]
Let the bottom padding be equal to the top one
image

**Comment by AlicjaSwierad** [comment]
- Advanced Search Guide and Exact Match - Font Size: 16px Medium (500)
- Switch height - 32px
- Clear Advanced Search 
- Align to the right, as in Figma

**Comment by jarekzet** [comment]
addedd all mods montioned above and in figma

image

**Comment by Marcelinna** [comment]
@jarekzet When I move the mouse under Clear Advanced Search I see the wrong pointer

**Comment by Marcelinna** [comment]
@jarekzet Please change text from Enter a valid DOI or Handle format. DOI example: 10.1038/nature25715; Handle example: 11356/1451.  to Enter a valid DOI format. Example: 10.1038/nature.25715

**Comment by Marcelinna** [comment]
@jarekzet I think we have bigger space for DOI
image

**Comment by Marcelinna** [comment]
@jarekzet Problem with tooltip for Exact match
image

**Comment by AlicjaSwierad** [comment]
When transitioning from AS to BS, the exact match and magnifier change locations

**Comment by jarekzet** [comment]
Added all above mods to new search panel:

image

**Comment by AlicjaSwierad** [comment]
advanced search guide and search bar should be in one line

image

**Comment by jarekzet** [comment]
added search switch width mod

image

**Review by Marcelinna — APPROVED** [review]

**Review by Michal-Kolomanski — CHANGES_REQUESTED** [review]
Please fix:
- git history,
- changelog.md should be generated automatically and not manually,
- linter (commits should start with e.g. style:)

**Pull request closed without merging**
