### PR TITLE
Mobile view fix

### PR DESCRIPTION
**Pull request by jarekzet**
Added mods for mobile version of search results

#622

### CODE REVIEW

**Comment by agpul** [comment]
image
Add "Hide filters" button (the second one) under all filters.

**Comment by agpul** [comment]
I can't see "Login" possibility

**Comment by Marcelinna** [comment]
@aleksandrahojszyk @agpul it is ok, or we should make mobile view at higher resolution ?
image

**Comment by Marcelinna** [comment]
Guideines view 
image

**Comment by aleksandrahojszyk** [comment]
> @aleksandrahojszyk @agpul it is ok, or we should make mobile view at higher resolution ? image

I do agree to make mobile view starting from higher resolution

**Review by Marcelinna — APPROVED** [review]

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
