### PR TITLE
fix: add-adv-search-switch-button

### PR DESCRIPTION
**Pull request by maria-j-k**

### CODE REVIEW

**Review by Michal-Kolomanski — APPROVED** [review]
@Marcelinna please confirm that that this PR does the same as https://github.com/cyfronet-fid/eosc-search-service/pull/1273. 
Old PR should be closed.

**Review by Marcelinna — APPROVED** [review]

**Review by Marcelinna — CHANGES_REQUESTED** [review]
Please check style for 
image

**Comment by jarekzet** [comment]
added fix for bottom action links:

image

**Comment by Marcelinna** [comment]
@jarekzet plesase delete vertical line in Guidelines
image

**Comment by jarekzet** [comment]
vertical line in Guidelines deleted:

image

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
