### PR TITLE
fix: [#597] Adjust ordering and naming of filters

### LINKED ISSUE #597: Fix small bugs and adjust filters order in SS
1. "All catalogs" order and changes:
- [x] Research step
- [x] Type of research (change the name from Type of product to type of research)
- [x] Access right
- [x] Scientific discipline -> hide it until we will improve the quality of this filter
- [x] Language
- [x] Horizontal service
2. "Publications" order and changes:
- [x] Research step - to be hidden as it has only one value
- [x] Access right
- [x] Year range
- [x] Document type
- [x] Scientific domain -> hide it until we will improve the quality of this filter
- [x] Country
- [x] Language
- [x] Research community
- [x] Funder
- [x] Sustainable development goals (change name from SDG [Beta] to  Sustainable development goals)
3. Data:
- [x] Research step - to be hidden as it has only one value
- [x] Access right
- [x] Year range
- [x] Document type
- [x] Scientific domain -> hide it until we will improve the quality of this filter
- [x] Country
- [x] Language
- [x] Publisher
- [x] Research community
- [x] Funder
- [x] Sustainable development goals (change name from SDG [Beta] to  Sustainable development goals)
4. Software
- [x] Research step - to be hidden as it has only one value
- [x] Access right
- [x] Year range - to be removed
- [x] Document type -  to be hidden as it has only one value
- [x] Scientific domain  -> hide it until we will improve the quality of this filter
- [x] Country
- [x] Language
- [x] Publisher
- [x] Research community
- [x] Funder
- [x] Sustainable development goals (change name from SDG [Beta] to  Sustainable development goals)
5. Services 
- [x] Research step
- [x] Access type (change the name from Order type to access type)
- [x] Categories - to be removed
- [x] Scientific domains
- [x] Providers
- [x] Resource organisation - to be removed
- [x] Dedicated for
- [x] Related infrastructures and platforms -> Related scientific communities and platforms
- [x] Rating
- [x] Access restrictions (change from Country to  Access restrictions and in filters value change from world to none)
- [x] Horizontal services
6. Data sources
- [x] Research step
- [x] Access type (change the name from Order type to access type)
- [x] Categories - to be removed
- [x] Scientific domains
- [x] Providers
- [x] Resource organisation - to be removed
- [x] Dedicated for
- [x] Related infrastructures and platforms
- [x] Rating
- [x] Access restrictions (change from Country to  Access restrictions and in filters value change from world to none)
- [x] Horizontal services
7. Trainings
- [x] Research step - to be hidden as it has only one value
- [x] Access right
- [x] Resource type
- [x] Material type (format) (change the name from Content type to Material type (format)
- [x] Language
- [x] Organisation
- [x] Level of expertise
- [x] Target group
- [x] Duration
- [x] Version date
8. Other
- [x] Research step - to be hidden as it has only one value
- [x] Access right
- [x] Year range 
- [x] Document type 
- [x] Scientific domain  -> hide it until we will improve the quality of this filter
- [x] Country
- [x] Language
- [x] Publisher
- [x] Research community
- [x] Funder
- [x] Sustainable development goals (change name from SDG [Beta] to  Sustainable development goals)

### PR DESCRIPTION
**Pull request by wujuu**
Closes #597

### CODE REVIEW

**Comment by Marcelinna** [comment]
Publisher should be higher up as in the list
image
image

**Comment by Marcelinna** [comment]
Please restore Resource organistation, we have to first join Providers and Resource organistation but at a later date
image

**Comment by Marcelinna** [comment]
Please change this for datasources too
image

**Comment by wujuu** [comment]
Addressed comments and added rev 2

**Comment by Marcelinna** [comment]
Please change the order for services as for datasource
image

**Comment by wujuu** [comment]
Added rev 3

**Review by Marcelinna — APPROVED** [review]

**Review by tomaszandel — APPROVED** [review]

**Pull request merged**
