### PR TITLE
feat: [#782, #783] Add product type and access right labels

### LINKED ISSUE #782: Move the product type under the title and if necessary display it together with Document type
Acceptance criteria:
- [x] As a User I would like to see document type under the title (not above) and if possible it should be displayed together with "Document type" field

Products with document type:
- [x] Publication
- [x] Data
- [x] Training
- [x] Other

Tip:
image

Figma:
https://www.figma.com/file/pTiscgrb4ie8R57vJmEhyL/Boxy-Redesign?type=design&node-id=7-2879&mode=design&t=3kJavuus7ieNTgsJ-4

### LINKED ISSUE #783: Move the access type under the title and change the text into logo
Acceptance criteria:
- [x] As a User I would like to see the access type  as an icon under the title

Tip:
image

Figma:
https://www.figma.com/file/pTiscgrb4ie8R57vJmEhyL/Boxy-Redesign?type=design&node-id=7-2879&mode=design&t=3kJavuus7ieNTgsJ-4

### PR DESCRIPTION
**Pull request by wujuu**
Closes #782. Closes #783.

### CODE REVIEW

**Comment by Marcelinna** [comment]
image

**Comment by Marcelinna** [comment]
Make according with figma
image

**Comment by Marcelinna** [comment]
Make according with figma
image

FIGMA
image

**Comment by Marcelinna** [comment]
why do we have duplicates?
image

**Comment by aleksandrahojszyk** [comment]
change font size from 16 to 14 px in type : document type
Screenshot 2023-08-22 at 12 55 31

**Comment by wujuu** [comment]
@Marcelinna @agpul @aleksandrahojszyk I addressed the changes

**Comment by Marcelinna** [comment]
can you remove ":" in case of missing data
image

**Comment by Marcelinna** [comment]
Do we have another ticket for "Horizontal service" label ?
image

**Comment by Marcelinna** [comment]
@wujuu @agpul @aleksandrahojszyk 
shouldn't we standardize that we always add "Access" to the end?
image

**Comment by aleksandrahojszyk** [comment]
> @wujuu @agpul @aleksandrahojszyk shouldn't we standardize that we always add "Access" to the end? image

it should stay as it is, it is used in this way regulary across repositories

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
