### PR TITLE
732 add the feedback mechanism on every page in search service

### PR DESCRIPTION
**Pull request by Barmin93**

### CODE REVIEW

**Comment by Marcelinna** [comment]
I don't see feedback for on details page
image

**Comment by Barmin93** [comment]
> I don't see feedback for on details page image

Added

**Review by Michal-Kolomanski — APPROVED** [review]
LGTM :clap: 
I would only consider dynamically changing the background color (from black to white) and the color of a question mark (from white to black) of the feedback widget - when the feedback widget is on the footer. @agpul @aleksandrahojszyk 
image

**Comment by michal-szostak** [comment]
I think this is the PR which can be closed as #892 is the latest changes.

**Pull request closed without merging**
