### PR TITLE
search panel mods and guide mods

### LINKED ISSUE #965: UI for Advanced Search and AS Guide
As a scope of this issue:
- [ ] add proper styles to the AS Guide: https://beta.search.marketplace.eosc-portal.eu/asguide
- [ ] add proper styles to this view:
image
- [ ] this one should be also white:
image
- [ ] see comments in Figma to adjust the sizes of fonts and images: https://www.figma.com/file/thf78Tiwv9qNGuorwLG1ti/Search?type=design&node-id=691-1241&mode=design&t=XWXhk65fQaxf3FC1-0
- [] see figma for advanced search guide - the Instructions: https://www.figma.com/file/GKqwn5BIuvXg4YdLBsARIn/eosc?type=design&node-id=322%3A6517&mode=design&t=MyFWFI1wZXXFKMrl-1

### PR DESCRIPTION
**Pull request by jarekzet**
closes #965

image
https://www.figma.com/file/GKqwn5BIuvXg4YdLBsARIn/eosc?type=design&node-id=322-6517&mode=design

### CODE REVIEW

**Comment by Marcelinna** [comment]
Can you change the mouse style when I hover on the "Expand all" button to hand?

**Comment by Marcelinna** [comment]
image

**Comment by Marcelinna** [comment]
color 
image

**Comment by Marcelinna** [comment]
Add space between 1, 2, 3
image

**Comment by Marcelinna** [comment]
Can you delete the comma 
image

**Comment by Marcelinna** [comment]
image

**Comment by Marcelinna** [comment]
image

**Comment by Marcelinna** [comment]
image

**Comment by Marcelinna** [comment]
image

**Comment by Marcelinna** [comment]
change 
image

**Comment by Marcelinna** [comment]
Add space 
image

**Comment by Marcelinna** [comment]
Add EOSC
image

**Comment by eldenkat** [comment]
Text looks good for me. Have a general question, tho. @aleksandrahojszyk @AlicjaSwierad, since we've changed colors of "clear advanced search" etc. into white, shouldn't we adjust screenshots?
Just asking, no pressure.

**Review by eldenkat — APPROVED** [review]

**Review by Michal-Kolomanski — CHANGES_REQUESTED** [review]
Hello @jarekzet :blush:  
1) Please prefix your commit messages with e.g. feat: [#<pr number>] - that would fix the failing github action.
There are also different possibilities not only feat (feature) - it could also be:
- style:
- test:
- fix:
- etc.
- full list: https://www.conventionalcommits.org/en/v1.0.0/

2) Please also resolve conflicts

**Review by Michal-Kolomanski — APPROVED** [review]

**Pull request merged**
