### PR TITLE
filter panel mods

### PR DESCRIPTION
**Pull request by jarekzet**
mods according to #380

### CODE REVIEW

**Comment by Marcelinna** [comment]
image

**Comment by Marcelinna** [comment]
pr 
image

produkcja 
image

**Comment by jarekzet** [comment]
"Clear all" button was made smaller to better fit the available space in filter panel.

Added fix to better position button vs filter title.

**Comment by Michal-Kolomanski** [comment]
@jarekzet rebase this PR on the current development to repair GitHub actions

**Pull request closed without merging**
