### PR TITLE
feat: [#802] show scientific domain filter in all related collections

### LINKED ISSUE #802: Show scientific domain filter in all related collections
Show SD filter in:
- all
- OAG
- services
- data sources

### PR DESCRIPTION
**Pull request by Michal-Kolomanski**
closes #802

### CODE REVIEW

**Review by tomaszandel — APPROVED** [review]

**Comment by Marcelinna** [comment]
image
why number is not the same?

**Comment by Marcelinna** [comment]
this duplication is ok ?
image

**Comment by Michal-Kolomanski** [comment]
> this duplication is ok ? image

Data has been updated - eliminating duplicates. This should not be the issue anymore.

**Comment by Marcelinna** [comment]
Can we merge this ?
image

**Comment by Michal-Kolomanski** [comment]
> Can we merge this ? in another pr ? image

In different PR yes. Whole scientific domain mapping for tranings and guidelines needs to be done.

**Comment by Michal-Kolomanski** [comment]
> image why number is not the same?

Now the count number and the actual results number should be the same across all collections.

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
