### PR TITLE
[#272] improve the behavior of the search bar

### PR DESCRIPTION
**Pull request by danielkryska**
https://github.com/cyfronet-fid/eosc-search-service/issues/272

### CODE REVIEW

**Comment by danielkryska** [comment]
Except for using single `~` char, you proposed more sophisticated solutions after your research what happened to them?

**Comment by danielkryska** [comment]
In case of checklist before [`review`](https://github.com/cyfronet-fid/eosc-search-service/pull/315#issuecomment-1308823036). You changed only 1 place in the code with `metadata.queryMutator`. That's caused critical building errors in `aot` and `jot`. 

But you'll know it if you tried your solution first.

image

**Comment by danielkryska** [comment]
```bash
Error: apps/ui/src/app/collections/data/datasets/search-metadata.data.ts:23:3 - error TS2322: Type '{ id: string; facets: { document_type: { field: string; type: "terms"; limit: number; }; best_access_right: { field: string; type: "terms"; limit: number; }; language: { field: string; type: "terms"; limit: number; }; ... 6 more ...; research_community: { ...; }; }; queryMutator: (q: string) => string; params: { ......' is not assignable to type 'ICollectionSearchMetadata'.
  Object literal may only specify known properties, and 'queryMutator' does not exist in type 'ICollectionSearchMetadata'.

23   queryMutator: (q: string) => q,
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: apps/ui/src/app/components/filters/filter-multiselect/utils.ts:16:15 - error TS2339: Property 'queryMutator' does not exist on type 'ICollectionSearchMetadata'.

16   q: metadata.queryMutator(q),
                 ~~~~~~~~~~~~

**Comment by biometricsmw** [comment]
Hi @danielkryska, thank you very much for your valuable comments and all remarks. When it comes to the more sophisticated methodology of search, once again checked the results of it and it seems that my first impression was wrong. Usage of ^ does not change anything in our case (this impression was connected with the fact that the list of found records changes slightly - but only in order, no new records are added neither any is removed). I also once again read the documentation of the SOLR search and it seems that in our case (because the issue was related to mistake in the word - e.g., "algorihtm" instead of "algorithm") ~ will do the job.

Yesterday, I observed that not all files were added by me to the commit - I am extremely sorry for that - it was the main point of the issue. Before our daily, I will once again check the files and then prepare another commit.

**Comment by danielkryska** [comment]
@biometricsmw, thank you for your additional comment about in-depth solution research. 

Before the next `review` of the Pull Request, please:
- go through all checks listed above in the comments
- write in comments how `~` affect multiple words? Have you checked it?

In case of further review, it will be provided by @michal-szostak. In case of any concerns, ask him questions.

**Comment by danielkryska** [comment]
In the case of multiple words. I have tested `hw to` in `training` to find records starting with `How to ...`.

`hw to~`, which you proposed gave me 0 results
`"hw to"~`, gave me the result I wanted

**Comment by biometricsmw** [comment]
Hi @danielkryska , once again thanks for your comments! When it comes to the example you provided - I also perform it on my latest implementation - the one without "", and received plenty of results. Please take a look at the screenshot attached.
Screenshot 2022-11-10 091236

**Comment by eldenkat** [comment]
After entering the first letters of the name, four results with no relation pop up, only then the right person

**Comment by biometricsmw** [comment]
It seems that (from the code analysis) - the highest priority is for the title, then the authors are considered and finally the description. So it can be a reason why such strange results are also given. Right now, I prepared the same procedure as in the case of suggestions. It is more precise than previously proposed solution. However, I am waiting for your comments.

**Comment by danielkryska** [comment]
Maybe you should update the field's weights in `search-metadata.data.ts` > in the field `qf`.

**Comment by danielkryska** [comment]
You could also add an additional query parameter to a search request `q.op=AND`.

**Pull request closed without merging**
