### PR TITLE
Highlight matched searched phrases in a title, a description, and the tags.

### PR DESCRIPTION
**Pull request by danielkryska**
- [x] highlight matched phrases
- [x] add extended search configuration with description (**this feature doesn't change results, it's adding the possibility for further improvements**)
  look for: `backend/app/solr/operations.py`
- [x] show full length title always
- [x] update searched fields configuration (to search by authors, keywords)

### CODE REVIEW

**Comment by danielkryska** [comment]
Use cases:

Software:
"title":"Monkeypox Knowledge Graph: A semantic resource embedding biological and chemical entities"
"title":"COVID-19 Knowledge Graph: A semantic resource embedding biological and chemical entities"
Other:
title:"ENVRI SP - Dashboard State of the Environment - Ocean Indicators"
title:"Mapping the photic zone of the Mediterranean Sea"

**Comment by danielkryska** [comment]
Business logic
- [ ] add show more button if the description doesn't have highlights match
- [ ] cut the title if it doesn't contain a match
- [ ] check sorting by

**Comment by Marcelinna** [comment]
why the word "to" is a good match in this case?
image

**Comment by danielkryska** [comment]
e8e7ff

**Comment by aleksandrahojszyk** [comment]
Maximum lenght of description is 512 characters

**Comment by Marcelinna** [comment]
highlight in training doesn't work?
image
image

**Comment by agpul** [comment]
> highlight in training doesn't work? image image

We agreed that it will be improved in the next iteration.

**Comment by Marcelinna** [comment]
description is not visible

production
image

pr
image

**Review by Michal-Kolomanski — APPROVED** [review]
LGTM

**Pull request merged**
