### PR TITLE
New guidelines view

### PR DESCRIPTION
**Pull request by jarekzet**
First part of mods due to #796 
No RWD yet.

### CODE REVIEW

**Comment by jarekzet** [comment]
Added RWD look for this view.

**Comment by eldenkat** [comment]
With a 13.5 screen, the view is too stretched and inconsistent.

Zrzut ekranu 2023-08-16 084226

**Comment by Marcelinna** [comment]
@jarekzet why I have so much space below the footer?
image

**Comment by Marcelinna** [comment]
@jarekzet I don't see Integration Options on pr
image

**Comment by Marcelinna** [comment]
delete 
image

**Comment by Marcelinna** [comment]
Add link to the button 
image

**Comment by jarekzet** [comment]
added mods according to comments above:
image

**Comment by Marcelinna** [comment]
@jarekzet 
image

**Comment by jarekzet** [comment]
added access button width fix for mobile:
image

**Review by Marcelinna — APPROVED** [review]

**Review by Anok666 — APPROVED** [review]

**Pull request merged**
