### PR TITLE
fix: diable fuzzy search

### PR DESCRIPTION
**Pull request by michal-szostak**

### CODE REVIEW

**Review by Michal-Kolomanski — APPROVED** [review]
A not ideal but better solution

**Comment by Marcelinna** [comment]
text should be changed

figma
image

pr
image

**Comment by Marcelinna** [comment]
button should be on the same hight 
image

**Comment by Marcelinna** [comment]
master (https://eosc-user-dashboard.docker-fid.grid.cyf-kr.edu.pl/dashboard)
image

pr
image

**Pull request closed without merging**
